/**
 * Name : Arewa (Morountudun) Ojelade
 * Date : 1/31/2025
 * File Name: category.js
 * Course : CMSC 495 Capstone in Computer Science
 * Project : Expense Tracker Capstone Project
 * Description : The purpose of the category.js module is to provide 
 * compact functions to interact with the Category collection of
 * the Expense Tracker Accounts database.
 */

import Category from "./models/Category.js";
import connectDB from "./dbconnect.js";connectDB();

/**
 * Function to add a category to the Category collection of the 
 * Expense Tracker Accounts database.
 * @param {String} name - The name of the associated Category instance. 
 * @returns {Object} The created instance of the category object.
 */
const addCategory = async(name)=>{  
        const count = await Category.where("version").equals("1").countDocuments();
        const category = await Category.create({
            categoryID : count,
            name : name
        });
        
        console.log(category);
        return category;
};
/**
 * Function to retrieve a category name from the Category collection of the 
 * Expense Tracker Accounts database.
 * @param {String} categoryID - The unique categoryID of the Category instance. 
 * @returns {String} The name of the category object.
 * Returns null if :
 *      1. Invalid categoryID is provided.
 */
const getCategoryName = async(categoryID)=>{
    const category = await Category.findOne({categoryID : categoryID});
    console.log(category);
    if(category){
        return category.name;
    }
    return null;
};
/**
 * Function to retrieve a category object from the Category collection of the 
 * Expense Tracker Accounts database.
 * @param {String} categoryID - The unique categoryID of the Category instance. 
 * @returns {Object} The category instance of the Category object.
 * Returns null if :
 *      1. Invalid categoryID is provided.
 */
const getCategoryObject = async(categoryID)=>{
    
    const category = await Category.findOne({categoryID : parseInt(categoryID)});
    if(category){
        return category;
    }
    return null;
};
/**
 * Function to initialize the Category collection of the 
 * Expense Tracker Accounts database with generic categories. 
 * Each category owns a unique _id generated by MongoDB, and 
 * a unique categoryID utilized for application purposes.
 */
const initializeCategories = async() =>{
    const names = ["All","Transportation","Housing","Vehicle","Life & Entertainment",
                "Food & Drinks", "Health & Body", "Professional Development", "Income","Investments"];
    var category;
    names.forEach((name,index)=>{
        category = addCategory(name);
        console.log(category);
    });
   
};
/**
 * Function to delete the categories by the specified version in the 
 * Expense Tracker Accounts database. This function is designed for
 * internal database maintainance and is not exported from the module.
 * @param {Int32} version - The version of Category instances to be deleted. 
 * @returns {Object} The  deleted instances of the categories that match specified version.
 */
const deleteCategories = async(version) =>{
   
    const deleted = await Category.deleteMany({version : version});
    return deleted;
};
export {initializeCategories, addCategory, getCategoryName,
        getCategoryObject, deleteCategories
    };
